name: advanced_storybook
description: Advanced Storybook for creating and testing widgets on different platforms.
version: 1.0.2
homepage: https://github.com/alex-melnyk/advanced_storybook
repository: https://github.com/alex-melnyk/advanced_storybook
issue_tracker: https://github.com/alex-melnyk/advanced_storybook/issues
documentation: https://github.com/alex-melnyk/advanced_storybook/blob/master/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  collection: ^1.15.0
  device_preview: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.alexmelnyk.advanced_storybook
        pluginClass: AdvancedStorybookPlugin
      ios:
        pluginClass: AdvancedStorybookPlugin
      linux:
        pluginClass: AdvancedStorybookPlugin
      macos:
        pluginClass: AdvancedStorybookPlugin
      windows:
        pluginClass: AdvancedStorybookPlugin
      web:
        pluginClass: AdvancedStorybookWeb
        fileName: advanced_storybook_web.dart
