name: advanced_storybook
description: Advanced Storybook
version: 0.0.1
homepage: https://github.com/alex-melnyk/advanced_storybook
repository: https://github.com/alex-melnyk/advanced_storybook
issue_tracker: https://github.com/alex-melnyk/advanced_storybook/issues
documentation: https://github.com/alex-melnyk/advanced_storybook/blob/master/README.md

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  device_preview: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.alexmelnyk.advanced_storybook
        pluginClass: AdvancedStorybookPlugin
      ios:
        pluginClass: AdvancedStorybookPlugin
      linux:
        pluginClass: AdvancedStorybookPlugin
      macos:
        pluginClass: AdvancedStorybookPlugin
      windows:
        pluginClass: AdvancedStorybookPlugin
      web:
        pluginClass: AdvancedStorybookWeb
        fileName: advanced_storybook_web.dart
